.TH owcli 1  "06/2010" "version 0.4" "USER COMMANDS"
.SH NAME
owcli \- The OntoWiki Command Line Interface
.SH SYNOPSIS
.B owcli
[options]
.SH DESCRIPTION
The OntoWiki Command Line Interface is a script-able and pipe-able PHP application for the Unix command line to help you to manage your OntoWiki knowledge bases.
.PP
The OntoWiki Command Line Interface is a specialised JSON/RPC client for the OntoWiki JSON/RPC component. You need a working OntoWiki with this component activated and it depend on your OntoWiki version, which remote procedures you can use.
.PP
I recommend to use the zsh together with OntoWiki because of the existing zsh auto-completion function which make the work with owcli much easier.
.PP
A detailed documentation together with many examples can be accessed at http://code.google.com/p/ontowiki/wiki/CommandLineInterface.
.SH OPTIONS
.TP
\--help
to display all options with description (this man page is only a dummy with examples)
.SH EXAMPLES
.TP
List all models (of the default wiki):
.B owcli -l
.TP
List all existing remote procedures (of the default wiki):
.B owcli -p
.TP
Drop a model (delete all statements):
.B owcli -m http://localhost/model1/ \-e model:drop
.TP
Create a new Model and add tripels from a file:
.B owcli -m http://localhost/model1/ \-e model:create model:add -i file.rdf

.SH AUTHOR
Sebastian Tramp (mail@sebastian.tramp.name)
.SH SEE ALSO
http://code.google.com/p/ontowiki/wiki/CommandLineInterface

